### ISSUE TITLE
How to use it with ColorOutput::RGBA?

### ISSUE THREAD

**Issue by Boscop** [kornelski/image-gif-dispose#1]
I want to render gifs using glium so I need the frame data as RGBA, as described here: https://github.com/PistonDevelopers/image-gif/issues/32#issue-200563939

How can I use ColorOutput::RGBA with this crate? :)

**Comment by kornelski** [comment]
`screen.pixels` is RGBA. It needs indexed input in order to produce RGBA output.

**Comment by Boscop** [comment]
Thanks, and does Screen expand all the frames to the size of the gif (padded with transparency), placing them at their position?

**Comment by kornelski** [comment]
Yes, of course.
