### ISSUE TITLE
No transparency

### ISSUE THREAD

**Issue by AngReload** [kornelski/image-gif-dispose#2]
Any GIFs having transparent pixels are decoded as full opaque.
For example: https://upload.wikimedia.org/wikipedia/commons/c/ce/Transparent.gif
```rust
#[test]
fn minimal_example() {
    let file = File::open("tests/Transparent.gif").unwrap();
    let mut decoder = gif::Decoder::new(file);

    decoder.set(gif::ColorOutput::Indexed);

    let mut reader = decoder.read_info().unwrap();

    let mut screen = gif_dispose::Screen::new_reader(&reader);
    while let Some(frame) = reader.read_next_frame().unwrap() {
        screen.blit_frame(&frame).unwrap();

        let mut t = "alpha == 255";
        for pixel in screen.pixels.as_ref() {
            if pixel.a != 255 {
                t = "transparent";
            }
        }
        println!("{}", t); // "alpha == 255"
    }
}
```

**Comment by kornelski** [comment]
This crate doesn't support `gif::ColorOutput::Indexed`

**Comment by kornelski** [comment]
Thanks for the report.

I've assumed that when a GIF has a background color set, it wants to have a background. This image does set background color to index 0.

**Comment by kornelski** [comment]
For this image I think fe9b8a307a6a81b897f3b52dcf3dc6db37789470 solves it.

I've also found another issue, which I don't know how to solve: https://github.com/PistonDevelopers/image-gif/issues/52

**Comment by AngReload** [comment]
Okay, this only works for the first frame. Looks like we have to wait a decision on the issue gif-crate.
